#!/bin/bash

echo "21" > /bin/versao
echo "21" > /home/versao
echo "21" > /home/sshplus
echo "by: @crazy_vpn" > /usr/lib/licence
echo 'by: @crazy_vpn' > /usr/lib/sshplus
echo "0" > /etc/SSHPlus/Exp

rm -rf /etc/SSHPlus/bot /etc/SSHPlus/ShellBot.sh /etc/SSHPlus/cabecalho /etc/SSHPlus/proxy.py > /dev/null 2>&1

echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
[[ ! -d /etc/SSHPlus ]] && mkdir /etc/SSHPlus
[[ ! -d /etc/SSHPlus/senha ]] && mkdir /etc/SSHPlus/senha
[[ ! -e /etc/SSHPlus/Exp ]] && touch /etc/SSHPlus/Exp
[[ ! -d /etc/SSHPlus/userteste ]] && mkdir /etc/SSHPlus/userteste
if ps x | grep "bot_plus"|grep -v grep 1>/dev/null 2>/dev/null; then
	pidbot_plus=$(ps x|grep "bot_plus"|awk -F "pts" {'print $1'})
    kill -9 $pidbot_plus > /dev/null 2>&1
    screen -wipe > /dev/null 2>&1
fi
wget https://github.com/SSHPLUS/ssh/raw/master/addhost.sh -O /bin/addhost > /dev/null 2>&1
chmod +x /bin/addhost
wget https://github.com/SSHPLUS/ssh/raw/master/verifatt.sh -O /bin/verifatt > /dev/null 2>&1
chmod +x /bin/verifatt
wget https://github.com/SSHPLUS/ssh/raw/master/verifbot.sh -O /bin/verifbot > /dev/null 2>&1
chmod +x /bin/verifbot
wget https://github.com/SSHPLUS/ssh/raw/master/alterarsenha.sh -O /bin/alterarsenha > /dev/null 2>&1
chmod +x /bin/alterarsenha
wget https://github.com/SSHPLUS/ssh/raw/master/criarusuario.sh -O /bin/criarusuario > /dev/null 2>&1
chmod +x /bin/criarusuario
wget https://github.com/SSHPLUS/ssh/raw/master/delhost.sh -O /bin/delhost > /dev/null 2>&1
chmod +x /bin/delhost
wget https://github.com/SSHPLUS/ssh/raw/master/expcleaner.sh -O /bin/expcleaner > /dev/null 2>&1
chmod +x /bin/expcleaner
wget https://github.com/SSHPLUS/ssh/raw/master/mudardata.sh -O /bin/mudardata > /dev/null 2>&1
chmod +x /bin/mudardata
wget https://github.com/SSHPLUS/ssh/raw/master/criarteste.sh -O /bin/criarteste > /dev/null 2>&1
chmod +x /bin/criarteste
wget https://github.com/SSHPLUS/ssh/raw/master/remover.sh -O /bin/remover > /dev/null 2>&1
chmod +x /bin/remover
wget https://github.com/SSHPLUS/ssh/raw/master/alterarlimite.sh -O /bin/alterarlimite > /dev/null 2>&1
chmod +x /bin/alterarlimite
wget https://github.com/SSHPLUS/ssh/raw/master/ajuda.sh -O /bin/ajuda > /dev/null 2>&1
chmod +x /bin/ajuda
wget https://github.com/SSHPLUS/ssh/raw/master/sshmonitor.sh -O /bin/sshmonitor > /dev/null 2>&1
chmod +x /bin/sshmonitor
wget https://github.com/SSHPLUS/ssh/raw/master/badvpn.sh -O /bin/badvpn > /dev/null 2>&1
chmod +x /bin/badvpn
wget https://github.com/SSHPLUS/ssh/raw/master/userbackup.sh -O /bin/userbackup > /dev/null 2>&1
chmod +x /bin/userbackup
wget https://github.com/SSHPLUS/ssh/raw/master/blockt.sh -O /bin/blockt > /dev/null 2>&1
chmod +x /bin/blockt
wget https://github.com/SSHPLUS/ssh/raw/master/otimizar.sh -O /bin/otimizar > /dev/null 2>&1
chmod +x /bin/otimizar
wget https://github.com/SSHPLUS/ssh/raw/master/menu.sh -O /bin/menu > /dev/null 2>&1
chmod +x /bin/menu
wget https://github.com/SSHPLUS/ssh/raw/master/speedtest.sh -O /bin/speedtest > /dev/null 2>&1
chmod +x /bin/speedtest
wget https://github.com/SSHPLUS/ssh/raw/master/banner.sh -O /bin/banner > /dev/null 2>&1
chmod +x /bin/banner
wget https://github.com/SSHPLUS/ssh/raw/master/senharoot.sh -O /bin/senharoot > /dev/null 2>&1
chmod +x /bin/senharoot
wget https://github.com/SSHPLUS/ssh/raw/master/reiniciarservicos.sh -O /bin/reiniciarservicos > /dev/null 2>&1
chmod +x /bin/reiniciarservicos
wget https://github.com/SSHPLUS/ssh/raw/master/reiniciarsistema.sh -O /bin/reiniciarsistema > /dev/null 2>&1
chmod +x /bin/reiniciarsistema
wget https://github.com/SSHPLUS/ssh/raw/master/attscript.sh -O /bin/attscript > /dev/null 2>&1
chmod +x /bin/attscript
wget https://github.com/SSHPLUS/ssh/raw/master/conexao.sh -O /bin/conexao > /dev/null 2>&1
chmod +x /bin/conexao
wget https://github.com/SSHPLUS/ssh/raw/master/detalhes.sh -O /bin/detalhes > /dev/null 2>&1
chmod +x /bin/detalhes
wget https://github.com/SSHPLUS/ssh/raw/master/droplimiter.sh -O /bin/droplimiter > /dev/null 2>&1
chmod +x /bin/droplimiter
wget https://github.com/SSHPLUS/ssh/raw/master/delscript.sh -O /bin/delscript > /dev/null 2>&1
chmod +x /bin/delscript
wget https://github.com/SSHPLUS/ssh/raw/master/botssh.sh -O /bin/botssh > /dev/null 2>&1
chmod +x /bin/botssh
wget https://github.com/SSHPLUS/ssh/raw/master/infousers.sh -O /bin/infousers > /dev/null 2>&1
chmod +x /bin/infousers
wget https://github.com/SSHPLUS/ssh/raw/master/limiter.sh -O /bin/limiter > /dev/null 2>&1
chmod +x /bin/limiter
wget https://github.com/SSHPLUS/ssh/raw/master/uexpired.sh -O /bin/uexpired > /dev/null 2>&1
chmod +x /bin/uexpired
wget https://github.com/SSHPLUS/ssh/raw/master/etc/cabecalho -O /etc/SSHPlus/cabecalho > /dev/null 2>&1
chmod +x /etc/SSHPlus/cabecalho
wget https://github.com/SSHPLUS/ssh/raw/master/etc/bot -O /etc/SSHPlus/bot > /dev/null 2>&1
chmod +x /etc/SSHPlus/bot
wget https://github.com/SSHPLUS/ssh/raw/master/etc/proxy.py -O /etc/SSHPlus/proxy.py > /dev/null 2>&1
chmod +x /etc/SSHPlus/proxy.py
wget https://github.com/SSHPLUS/ssh/raw/master/sshplus -O /usr/lib/sshplus > /dev/null 2>&1
chmod +x /usr/lib/sshplus
wget https://github.com/SSHPLUS/ssh/raw/master/fix.sh -O /home/fix > /dev/null 2>&1
chmod +x /home/fix
[[ ! -d /etc/bot ]] && mkdir /etc/bot
[[ ! -d /etc/bot/info-users ]] && mkdir /etc/bot/info-users
[[ ! -d /etc/bot/arquivos ]] && mkdir /etc/bot/arquivos
[[ ! -d /etc/bot/revenda ]] && mkdir /etc/bot/revenda
[[ ! -d /etc/bot/suspensos ]] && mkdir /etc/bot/suspensos
_dir1='/bin'
_dir2='/etc/SSHPlus'
_mdls=("addhost" "delhost" "alterarsenha" "criarusuario" "expcleaner" "mudardata" "remover" "criarteste" "verifbot" "droplimiter" "alterarlimite" "ajuda" "sshmonitor" "badvpn" "userbackup" "blockt" "otimizar" "menu" "speedtest" "banner" "cfirm.py" "senharoot" "reiniciarservicos" "reiniciarsistema" "attscript" "conexao" "delscript" "detalhes" "botssh" "infousers" "verifatt" "limiter" "uexpired" "cabecalho" "bot" "proxy.py")

_arq_host="/etc/hosts"
_host[0]="d1n212ccp6ldpw.cloudfront.net"
_host[1]="dns.whatsapp.net"
_host[2]="portalrecarga.vivo.com.br/recarga"
_host[3]="navegue.vivo.com.br/controle/"
_host[4]="navegue.vivo.com.br/pre/"
_host[5]="www.whatsapp.net"
_host[6]="/SSHPLUS?"
for host in ${_host[@]}; do
	if [[ "$(grep -w "$host" $_arq_host | wc -l)" = "0" ]]; then
		sed -i "3i\127.0.0.1 $host" $_arq_host
	fi
done

service ssh restart
[[ ! -e /etc/autostart ]] && {
echo '#!/bin/bash
clear
#INICIO AUTOMATICO' > /etc/autostart
chmod +x /etc/autostart
}
#INICIO
[[ $(crontab -l|grep -c "uexpired") = '0' ]] && (crontab -l 2>/dev/null; echo "0 */6 * * * /bin/uexpired") | crontab -
[[ $(crontab -l|grep -c "verifatt") = '0' ]] && (crontab -l 2>/dev/null; echo "@daily /bin/verifatt") | crontab -
[[ $(crontab -l|grep -c "autostart") = '0' ]] && (crontab -l 2>/dev/null; echo "@reboot /etc/autostart") | crontab -
wget -qO- https://github.com/SSHPLUS/ssh/raw/master/versao |sed -n '1 p' |cut -d' ' -f2 > /bin/versao && cat /bin/versao > /home/sshplus
service ssh restart > /dev/null 2>&1
[[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) != '0' ]] && {
[[ ! -e "/etc/SSHPlus/ShellBot.sh" ]] && wget -qO- https://raw.githubusercontent.com/shellscriptx/shellbot/master/ShellBot.sh > /etc/SSHPlus/ShellBot.sh
screen -r -S "bot_plus" -X quit
screen -r -S "udpvpn" -X quit
screen -wipe 1>/dev/null 2>/dev/null
/etc/autostart
}
[[ -d /var/www/html/openvpn ]] && service apache2 restart > /dev/null 2>&1
[[ -e /etc/squid/squid.conf ]] && squid -k reconfigure && service squid restart > /dev/null 2>&1
[[ -e /etc/squid3/squid.conf ]] && squid3 -k reconfigure && service squid3 restart > /dev/null 2>&1
